info:
  component: zuul server app
spring:
  application:
    name: zuul    
zuul:    
  routes:
    account-service:
      path: /account-service/**
      serviceId: account-service
        
    customer-service:
      path: /customer-service/**
      serviceId: customer-service
  sensitive-headers:
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true   
      